Transform: AWS::Serverless-2016-10-31

Resources:
  LayerBase:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/base

  LayerScraping:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/scraping

  LayerFeedparser:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/feedparser

  ParameterLayerArnBase:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /Golden/Layer/Base
      Type: String
      Value: !Ref LayerBase

  ParameterLayerArnScraping:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /Golden/Layer/Scraping
      Type: String
      Value: !Ref LayerScraping

  ParameterLayerArnFeedparser:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /Golden/Layer/Feedparser
      Type: String
      Value: !Ref LayerFeedparser
