name: deploy

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  SAM_ARTIFACT_BUCKET: ${{ secrets.SAM_ARTIFACT_BUCKET }}
  ROLE_CLOUDFORMATION_DEPLOY: ${{ secrets.ROLE_CLOUDFORMATION_DEPLOY }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9.13
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.ROLE_GITHUB_ACTIONS_CLOUDFORMATION_DEPLOY }}
      - uses: aws-actions/setup-sam@v2
      - run: pip install poetry
      - run: make build
      - run: make package
      - run: tar cf layers.tar *
      - uses: actions/upload-artifact@v3
        with:
          name: layers.tar
          path: layers.tar
      - run: make deploy
